services:
  - type: web
    name: sap
    runtime: node
    repo: https://github.com/Youpi-Corp/sap-ts
    plan: free
    envVars:
      - key: BUN_VERSION
        value: 1.1.0
      - key: PORT
        value: 8080
    region: frankfurt
    buildCommand: bun install
    startCommand: bun start
version: "1"
