# filepath: d:\Github\Brainforest\sap\.github\workflows\deploy.yml
name: Deploy Backend to VM

on:
  push:
    branches:
      - main # Or your deployment branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest # Or lock to a specific version

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build project
        run: bun run build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            dist/
            package.json
            bun.lockb
            drizzle/       # Add the drizzle folder containing SQL migrations
            # Add any other files needed for production

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: Production # Add this line to target the Production environment
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: ./deploy_package # Download to a temporary directory

      - name: List downloaded artifact contents # New step
        run: ls -la ./deploy_package

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VM # Renamed - Only ensures directory exists now
        run: |
          echo "Ensuring deployment directory exists on VM..."
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "mkdir -p ${{ secrets.DEPLOY_PATH }}"

      - name: Sync files and Restart application via PM2 # Renamed and modified
        env:
          # Make secrets available to the rsync/ssh step
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: ${{ secrets.PORT }}
        run: |
          echo "Syncing files via rsync..."
          # Ensure rsync copies the drizzle folder too
          rsync -avz --delete ./deploy_package/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_PATH }}/

          echo "Running commands on VM..."
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            echo "Changing directory to ${{ secrets.DEPLOY_PATH }}"
            cd ${{ secrets.DEPLOY_PATH }} || exit 1 # Exit if cd fails

            # Export environment variables for the PM2 process
            export NODE_ENV="production"
            export PORT="${PORT:-8080}"
            export DATABASE_URL="${DATABASE_URL}"
            export JWT_SECRET="${JWT_SECRET}"

            # Install production dependencies directly on the VM
            echo "Installing production dependencies..."
            bun install --production --frozen-lockfile

            # Run database migrations using the compiled script via npm script
            echo "Running database migrations..."
            bun run migrate # Use the new npm script

            # Start or restart the application using PM2 via npm script
            echo "Starting/Restarting application with PM2 via npm start script..."
            # Tell PM2 to run the 'start' script from package.json
            /usr/local/bin/pm2 start npm --name brainforest-api -- run start --update-env
            # Add a small delay
            sleep 2
            /usr/local/bin/pm2 save # Save the process list
            echo "Deployment complete. Application managed by PM2."
          EOF
