name: Deploy to Production

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  APP_NAME: brainforest-api
  DEPLOY_PATH: ~/brainforest-api

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies and build
        run: |
          bun install --frozen-lockfile
          bun run build

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          # Create deployment directory
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "mkdir -p ${{ env.DEPLOY_PATH }}"          # Sync files (exclude unnecessary files)
          rsync -avz --delete \
            --exclude='.git' \
            --exclude='node_modules' \
            --exclude='.env*' \
            --exclude='*.log' \
            ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ env.DEPLOY_PATH }}/

      - name: Install and restart application
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: ${{ secrets.PORT }}
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -e
            cd ${{ env.DEPLOY_PATH }}
            
            # Set environment variables for this session
            export NODE_ENV=production
            export DATABASE_URL="${{ secrets.DATABASE_URL }}"
            export JWT_SECRET="${{ secrets.JWT_SECRET }}"
            export PORT="${{ secrets.PORT }}"
            
            # Install production dependencies
            bun install --production --frozen-lockfile
            
            # Run migrations
            bun run migrate            # Install PM2 if not already installed
            if ! command -v pm2 &> /dev/null; then
              npm install -g pm2
            fi
            
            # Create ecosystem file for proper environment handling
            echo "module.exports = {" > ecosystem.config.js
            echo "  apps: [{" >> ecosystem.config.js
            echo "    name: '${{ env.APP_NAME }}'," >> ecosystem.config.js
            echo "    script: 'dist/index.js'," >> ecosystem.config.js
            echo "    interpreter: 'bun'," >> ecosystem.config.js
            echo "    cwd: '${{ env.DEPLOY_PATH }}'," >> ecosystem.config.js
            echo "    env: {" >> ecosystem.config.js
            echo "      NODE_ENV: 'production'," >> ecosystem.config.js
            echo "      PORT: '${{ secrets.PORT }}'," >> ecosystem.config.js
            echo "      DATABASE_URL: '${{ secrets.DATABASE_URL }}'," >> ecosystem.config.js
            echo "      JWT_SECRET: '${{ secrets.JWT_SECRET }}'" >> ecosystem.config.js
            echo "    }," >> ecosystem.config.js
            echo "    instances: 1," >> ecosystem.config.js
            echo "    autorestart: true," >> ecosystem.config.js
            echo "    watch: false," >> ecosystem.config.js
            echo "    max_memory_restart: '1G'" >> ecosystem.config.js
            echo "  }]" >> ecosystem.config.js
            echo "};" >> ecosystem.config.js
            
            # Create logs directory
            mkdir -p logs
            
            # Restart PM2 process
            pm2 delete ${{ env.APP_NAME }} 2>/dev/null || true
            
            # Start using ecosystem file
            pm2 start ecosystem.config.js
            pm2 save
            
            # Health check
            sleep 3
            if pm2 list | grep -q "${{ env.APP_NAME }}.*online"; then
              echo "✅ Deployment successful"
            else
              echo "❌ Deployment failed"
              pm2 logs ${{ env.APP_NAME }} --lines 10
              exit 1
            fi
          EOF
